package com.giovicente.append.items;

import java.util.Arrays;
import java.util.List;

public class ItemsBuilder {

    public static List<String> buildList1() {
        return List.of(
                "Apple",
                "Banana",
                "Orange",
                "Pineapple",
                "Mango",
                "Strawberry",
                "Blueberry",
                "Grapes",
                "Watermelon",
                "Kiwi",
                "Peach",
                "Pear",
                "Plum",
                "Cherry",
                "Papaya",
                "Apricot",
                "Blackberry",
                "Cantaloupe",
                "Date",
                "Elderberry",
                "Fig",
                "Grapefruit",
                "Honeydew",
                "Jackfruit",
                "Kumquat",
                "Lemon",
                "Lychee",
                "Nectarine",
                "Olive",
                "Passionfruit",
                "Quince",
                "Raspberry",
                "Starfruit",
                "Tangerine",
                "Ugli fruit",
                "Vanilla Bean",
                "Watercress",
                "Xigua",
                "Yellow Passionfruit",
                "Zucchini",
                "Coconut",
                "Durian",
                "Acai",
                "Cranberry",
                "Dragonfruit",
                "Persimmon",
                "Rambutan",
                "Sapote",
                "Tamarind"
        );
    }

    public static List<String> buildList2() {
        return List.of(
                "Apple",
                "Banana",
                "Orange",
                "Pineapple",
                "Mango",
                "Strawberry",
                "Blueberry",
                "Grapes",
                "Watermelon",
                "Kiwi",
                "Peach",
                "Pear",
                "Plum",
                "Cherry",
                "Papaya",
                "Apricot",
                "Blackberry",
                "Cantaloupe",
                "Date",
                "Elderberry",
                "Fig",
                "Grapefruit",
                "Honeydew",
                "Jackfruit",
                "Kumquat",
                "Lemon",
                "Lychee",
                "Nectarine",
                "Olive",
                "Passionfruit",
                "Quince",
                "Raspberry",
                "Starfruit",
                "Tangerine",
                "Ugli fruit",
                "Vanilla Bean",
                "Watercress",
                "Xigua",
                "Yellow Passionfruit",
                "Zucchini",
                "Coconut",
                "Durian",
                "Acai",
                "Cranberry",
                "Dragonfruit",
                "Persimmon",
                "Rambutan",
                "Tomato",
                "Tamarind"
        );
    }
}
